using Mutagen.Bethesda;
using Mutagen.Bethesda.Plugins;
using Mutagen.Bethesda.Plugins.Cache;
using Mutagen.Bethesda.Plugins.Order;
using Mutagen.Bethesda.Skyrim;
using Mutagen.Bethesda.Synthesis;

namespace RequiemAutoNPCPatcher3T;

public class Program
{
    private static Lazy<Settings> _settings = null!;
    private static Settings Config => _settings.Value;

    public static async Task<int> Main(string[] args) =>
        await SynthesisPipeline.Instance
            .AddPatch<ISkyrimMod, ISkyrimModGetter>(RunPatch)
            .SetAutogeneratedSettings("Settings", "settings.json", out _settings)
            .SetTypicalOpen(GameRelease.SkyrimSE, "RequiemAutoNPCPatcher3T.esp")
            .Run(args);

    public static void RunPatch(IPatcherState<ISkyrimMod, ISkyrimModGetter> state)
    {
        if (Config.TargetMods.Count == 0)
        {
            Console.WriteLine("No target mods listed. Add the plugins you want rebalanced in this patcher's settings.");
            return;
        }

        // ------------------------------------------------------------------ the filtered view
        //
        // This patcher runs BEFORE the Reqtificator and the Reqtificator is regenerated afterwards, so
        // every read resolves the winner with the generated plugins REMOVED. Reading
        // 'Requiem for the Indifferent.esp' would mean copying values a tool computed and is about to
        // recompute, and hand-placing perks the next run assigns itself.
        var blocked = Config.GeneratedOutputPlugins.ToHashSet();
        blocked.Add(state.PatchMod.ModKey);

        var visible = state.LoadOrder.ListedOrder
            .Where(listing => listing.Enabled && listing.Mod is not null && !blocked.Contains(listing.ModKey))
            .Select(listing => listing.Mod!)
            .ToArray();

        var removed = state.LoadOrder.ListedOrder
            .Count(l => l.Enabled && l.Mod is not null && blocked.Contains(l.ModKey));

        var order = new LoadOrder<IModListing<ISkyrimModGetter>>(
            visible.Select(mod => new ModListing<ISkyrimModGetter>(mod, enabled: true)));
        var cache = order.ToImmutableLinkCache<ISkyrimMod, ISkyrimModGetter>();

        Console.WriteLine($"Reading {visible.Length} plugin(s); {removed} generated plugin(s) excluded from every lookup.");

        // ------------------------------------------------------------------ scope
        var targets = Config.TargetMods.Except(Config.ExcludedMods).ToHashSet();
        foreach (var missing in targets.Where(t => !state.LoadOrder.ContainsKey(t)).ToList())
        {
            Console.WriteLine($"WARNING: target plugin '{missing}' is not in the load order — skipped.");
            targets.Remove(missing);
        }
        if (targets.Count == 0) return;

        var donorPlugins = Config.DonorPlugins.ToHashSet();
        var excludedNpcs = Config.ExcludedNpcs.Select(l => l.FormKey).ToHashSet();

        var log = new PatchLog(Config.VerboseLog);
        var view = new ActorView(cache);
        var classifier = new Classifier(cache, view);
        var npcPatcher = new NpcPatcher(cache, view, Config, log, donorPlugins);
        var racePatcher = new RacePatcher(cache, Config, log);

        // ------------------------------------------------------------------ donor pool
        var winningNpcs = order.PriorityOrder.Npc().WinningOverrides().ToArray();
        var donors = new DonorIndex(winningNpcs, donorPlugins, cache, view, classifier);
        Console.WriteLine($"Donor pool: {donors.ActorCount} actor(s) across {donors.RaceCount} race(s), of which {donors.CasterCount} caster(s).");

        // Every NPC the target mods touch but do not define. Built once — asking the load order per
        // actor is O(actors x plugins) on a mod that adds a thousand of them.
        var touchedByTarget = Config.PatchOverriddenRecords
            ? state.LoadOrder.ListedOrder
                .Where(l => targets.Contains(l.ModKey) && l.Mod is not null)
                .SelectMany(l => l.Mod!.Npcs.Select(n => n.FormKey))
                .ToHashSet()
            : new HashSet<FormKey>();

        var rankFloor = Math.Clamp(Config.MinimumRank, 1, 6);
        var rankCeiling = Math.Clamp(Config.MaximumRank, rankFloor, 6);

        // ------------------------------------------------------------------ actors
        foreach (var npc in winningNpcs)
        {
            // A record defined elsewhere that a target mod merely overrides is out of scope unless the
            // user has explicitly asked for it: the stack already owns that record, and re-deriving it
            // would fight the stack.
            if (!targets.Contains(npc.FormKey.ModKey) && !touchedByTarget.Contains(npc.FormKey)) continue;
            if (excludedNpcs.Contains(npc.FormKey)) continue;
            if (npc.EditorID is not null && StackData.IsTombstone(npc.EditorID)) continue;

            var cls = classifier.Classify(npc, Config.FallbackArchetype);

            if (!cls.IsCombatant && !Config.PatchNonCombatants)
            {
                log.Note($"{Describe(npc)}: left alone — {cls.CombatantReason}.");
                continue;
            }

            switch (cls.Kind)
            {
                case ActorKind.Humanoid when Config.PatchHumanoids:
                {
                    var rank = Math.Clamp(NearestRank(view.IntendedLevel(npc)), rankFloor, rankCeiling);
                    var target = state.PatchMod.Npcs.GetOrAddAsOverride(npc);
                    if (!npcPatcher.ApplyBanditRank(npc, target, cls.Archetype, rank, cls))
                        state.PatchMod.Npcs.Remove(npc.FormKey);
                    break;
                }

                case ActorKind.Caster when Config.PatchCasters:
                {
                    var donor = donors.ForCaster(view.IntendedLevel(npc));
                    if (donor is null)
                    {
                        log.NeedsDecision($"{Describe(npc)}: a caster, but the donor plugins hold no caster comparable.");
                        break;
                    }
                    var target = state.PatchMod.Npcs.GetOrAddAsOverride(npc);
                    if (!npcPatcher.ApplyDonor(npc, target, donor, cls, "nearest caster by level"))
                        state.PatchMod.Npcs.Remove(npc.FormKey);
                    break;
                }

                case ActorKind.Creature when Config.PatchCreatures:
                {
                    var raceLink = view.RaceLink(npc);
                    if (raceLink is null || raceLink.IsNull)
                    {
                        log.Error($"{Describe(npc)}: no resolvable race.");
                        break;
                    }

                    var donorRace = ResolveDonorRace(raceLink.FormKey, donors);
                    if (donorRace is null)
                    {
                        log.NeedsDecision(
                            $"{Describe(npc)}: race {RaceName(raceLink.FormKey, cache)} has no comparable actor in the donor plugins.");
                        break;
                    }

                    var donor = donors.ForRace(donorRace.Value, view.IntendedLevel(npc));
                    if (donor is null) break;

                    var why = donorRace.Value == raceLink.FormKey
                        ? "same race, nearest by level"
                        : $"race override -> {RaceName(donorRace.Value, cache)}, nearest by level";

                    var target = state.PatchMod.Npcs.GetOrAddAsOverride(npc);
                    if (!npcPatcher.ApplyDonor(npc, target, donor, cls, why))
                        state.PatchMod.Npcs.Remove(npc.FormKey);
                    break;
                }
            }
        }

        // ------------------------------------------------------------------ races the mods define
        foreach (var race in order.PriorityOrder.Race().WinningOverrides())
        {
            if (!targets.Contains(race.FormKey.ModKey)) continue;

            var patched = false;
            Race? target = null;

            var overrideEntry = Config.RaceDonorOverrides
                .FirstOrDefault(o => o.TargetRace.FormKey == race.FormKey);

            if (overrideEntry is not null
                && !overrideEntry.DonorRace.IsNull
                && overrideEntry.DonorRace.TryResolve(cache, out var donorRace))
            {
                target = state.PatchMod.Races.GetOrAddAsOverride(race);
                patched |= racePatcher.Apply(race, target, donorRace);
            }

            target ??= state.PatchMod.Races.GetOrAddAsOverride(race);
            patched |= racePatcher.StripGiantStomp(race, target);

            if (!patched) state.PatchMod.Races.Remove(race.FormKey);
        }

        log.Summarise();
    }

    /// <summary>Rank levels are 3 / 7 / 10 / 12 / 19 / 24. Ties go to the higher rank: under-statting an
    /// enemy is the expensive mistake.</summary>
    private static int NearestRank(int level)
    {
        var best = 1;
        var bestDistance = int.MaxValue;
        for (var rank = 1; rank <= 6; rank++)
        {
            var distance = Math.Abs(StackData.RankLevels[rank] - level);
            if (distance <= bestDistance) { bestDistance = distance; best = rank; }
        }
        return best;
    }

    private static FormKey? ResolveDonorRace(FormKey race, DonorIndex donors)
    {
        if (donors.HasRace(race)) return race;

        var mapped = Config.RaceDonorOverrides
            .FirstOrDefault(o => o.TargetRace.FormKey == race && !o.DonorRace.IsNull);
        if (mapped is not null && donors.HasRace(mapped.DonorRace.FormKey)) return mapped.DonorRace.FormKey;

        return null;
    }

    private static string RaceName(FormKey race, ILinkCache cache) =>
        cache.TryResolve<IRaceGetter>(race, out var r)
            ? $"{r.EditorID ?? "<unnamed>"} ({race})"
            : race.ToString();

    private static string Describe(INpcGetter npc) =>
        $"{npc.EditorID ?? npc.Name?.String ?? "<unnamed>"} ({npc.FormKey})";
}
