using Mutagen.Bethesda;
using Mutagen.Bethesda.Plugins;
using Mutagen.Bethesda.Plugins.Cache;
using Mutagen.Bethesda.Plugins.Order;
using Mutagen.Bethesda.Skyrim;
using Mutagen.Bethesda.Synthesis;

namespace RequiemAutoNPCPatcher3T;

public class Program
{
    private static Lazy<Settings> _settings = null!;
    private static Settings Config => _settings.Value;

    public static async Task<int> Main(string[] args) =>
        await SynthesisPipeline.Instance
            .AddPatch<ISkyrimMod, ISkyrimModGetter>(RunPatch)
            .SetAutogeneratedSettings("Settings", "settings.json", out _settings)
            .SetTypicalOpen(GameRelease.SkyrimSE, "RequiemAutoNPCPatcher3T.esp")
            .Run(args);

    public static void RunPatch(IPatcherState<ISkyrimMod, ISkyrimModGetter> state)
    {
        if (Config.TargetMods.Count == 0)
        {
            Console.WriteLine("No target mods listed. Add the plugins you want rebalanced in this patcher's settings.");
            return;
        }

        // ------------------------------------------------------------------ the filtered view
        //
        // This patcher runs BEFORE the Reqtificator and the Reqtificator is regenerated afterwards, so
        // every read resolves the winner with the generated plugins REMOVED. Reading
        // 'Requiem for the Indifferent.esp' would mean copying values a tool computed and is about to
        // recompute, and hand-placing perks the next run assigns itself.
        var blocked = Config.GeneratedOutputPlugins.ToHashSet();
        blocked.Add(state.PatchMod.ModKey);

        var visible = state.LoadOrder.ListedOrder
            .Where(listing => listing.Enabled && listing.Mod is not null && !blocked.Contains(listing.ModKey))
            .Select(listing => listing.Mod!)
            .ToArray();

        var removed = state.LoadOrder.ListedOrder
            .Count(l => l.Enabled && l.Mod is not null && blocked.Contains(l.ModKey));

        var order = new LoadOrder<IModListing<ISkyrimModGetter>>(
            visible.Select(mod => new ModListing<ISkyrimModGetter>(mod, enabled: true)));
        var cache = order.ToImmutableLinkCache<ISkyrimMod, ISkyrimModGetter>();

        Console.WriteLine($"Reading {visible.Length} plugin(s); {removed} generated plugin(s) excluded from every lookup.");

        // ------------------------------------------------------------------ scope
        var targets = Config.TargetMods.Except(Config.ExcludedMods).ToHashSet();
        foreach (var missing in targets.Where(t => !state.LoadOrder.ContainsKey(t)).ToList())
        {
            Console.WriteLine($"WARNING: target plugin '{missing}' is not in the load order — skipped.");
            targets.Remove(missing);
        }
        if (targets.Count == 0) return;

        var donorPlugins = Config.DonorPlugins.ToHashSet();
        var excludedNpcs = Config.ExcludedNpcs.Select(l => l.FormKey).ToHashSet();

        var log = new PatchLog(Config.VerboseLog);
        var view = new ActorView(cache);
        var classifier = new Classifier(cache, view);
        var npcPatcher = new NpcPatcher(cache, view, Config, log, donorPlugins);
        var racePatcher = new RacePatcher(cache, Config, log);

        // ------------------------------------------------------------------ donor pool
        var winningNpcs = order.PriorityOrder.Npc().WinningOverrides().ToArray();
        var donors = new DonorIndex(winningNpcs, donorPlugins, cache, view, classifier);
        Console.WriteLine(
            $"Donor pool: {donors.ActorCount} actor(s) across {donors.RaceCount} race(s) — " +
            $"{donors.CasterCount} caster(s), {donors.GhostCount} ghost(s). " +
            $"{donors.RejectedCount} unique/summonable actor(s) refused as comparables.");

        // Every NPC the target mods touch but do not define. Built once — asking the load order per
        // actor is O(actors x plugins) on a mod that adds a thousand of them.
        var touchedByTarget = Config.PatchOverriddenRecords
            ? state.LoadOrder.ListedOrder
                .Where(l => targets.Contains(l.ModKey) && l.Mod is not null)
                .SelectMany(l => l.Mod!.Npcs.Select(n => n.FormKey))
                .ToHashSet()
            : new HashSet<FormKey>();

        var rankFloor = Math.Clamp(Config.MinimumRank, 1, 6);
        var rankCeiling = Math.Clamp(Config.MaximumRank, rankFloor, 6);

        // ------------------------------------------------------------------ actors
        foreach (var npc in winningNpcs)
        {
            // A record defined elsewhere that a target mod merely overrides is out of scope unless the
            // user has explicitly asked for it: the stack already owns that record, and re-deriving it
            // would fight the stack.
            if (!targets.Contains(npc.FormKey.ModKey) && !touchedByTarget.Contains(npc.FormKey)) continue;
            if (excludedNpcs.Contains(npc.FormKey)) continue;
            if (npc.EditorID is not null && StackData.IsTombstone(npc.EditorID)) continue;

            // A clone of a vanilla or stack actor is settled before anything else is considered: the
            // original is already balanced, so inheriting beats deriving.
            if (Config.InheritFromStackTemplates
                && npc.Configuration.TemplateFlags.HasFlag(NpcConfiguration.TemplateFlag.Traits)
                && npc.Template.TryResolve(cache) is INpcGetter original
                && !targets.Contains(original.FormKey.ModKey))
            {
                var clone = state.PatchMod.Npcs.GetOrAddAsOverride(npc);
                if (!npcPatcher.ApplyCloneInheritance(npc, clone, original))
                    state.PatchMod.Npcs.Remove(npc.FormKey);
                continue;
            }

            var cls = classifier.Classify(npc, Config.FallbackArchetype);

            if (cls.IsChild)
            {
                if (!Config.DeLevelChildren) continue;
                var child = state.PatchMod.Npcs.GetOrAddAsOverride(npc);
                if (!npcPatcher.ApplyChildLevel(npc, child, Config.ChildLevel))
                    state.PatchMod.Npcs.Remove(npc.FormKey);
                continue;
            }

            if (!cls.IsCombatant && !Config.PatchNonCombatants)
            {
                log.Note($"{Describe(npc)}: left alone — {cls.CombatantReason}.");
                continue;
            }

            switch (cls.Kind)
            {
                case ActorKind.Humanoid when Config.PatchHumanoids:
                {
                    var rank = Math.Clamp(NearestRank(view.IntendedLevel(npc)), rankFloor, rankCeiling);
                    var target = state.PatchMod.Npcs.GetOrAddAsOverride(npc);
                    if (!npcPatcher.ApplyBanditRank(npc, target, cls.Archetype, rank, cls))
                        state.PatchMod.Npcs.Remove(npc.FormKey);
                    break;
                }

                case ActorKind.Ghost when Config.PatchGhosts:
                {
                    var donor = donors.ForGhost(view.IntendedLevel(npc));
                    if (donor is null)
                    {
                        log.NeedsDecision($"{Describe(npc)}: a ghost, but the donor plugins hold no ghost comparable.");
                        break;
                    }
                    var target = state.PatchMod.Npcs.GetOrAddAsOverride(npc);
                    if (!npcPatcher.ApplyDonor(npc, target, donor, cls, "nearest ghost by level"))
                        state.PatchMod.Npcs.Remove(npc.FormKey);
                    break;
                }

                case ActorKind.Caster when Config.PatchCasters:
                {
                    var donor = donors.ForCaster(view.IntendedLevel(npc));
                    if (donor is null)
                    {
                        log.NeedsDecision($"{Describe(npc)}: a caster, but the donor plugins hold no caster comparable.");
                        break;
                    }
                    var target = state.PatchMod.Npcs.GetOrAddAsOverride(npc);
                    if (!npcPatcher.ApplyDonor(npc, target, donor, cls, "nearest caster by level"))
                        state.PatchMod.Npcs.Remove(npc.FormKey);
                    break;
                }

                case ActorKind.Creature when Config.PatchCreatures:
                {
                    if (view.RaceKey(npc) is not { } raceKey)
                    {
                        // Not an error. The actor's Traits come from a leveled list whose entries name no
                        // usable race, so there is nothing to compare it against — and its own Race field
                        // is the CK's FoxRace placeholder, which would be a lie to act on.
                        log.Note($"{Describe(npc)}: race comes from a leveled list with no resolvable entries — left alone.");
                        break;
                    }

                    var donorRace = ResolveDonorRace(raceKey, donors, cache);
                    if (donorRace is null)
                    {
                        log.NeedsDecision(
                            $"{Describe(npc)}: race {RaceName(raceKey, cache)} has no comparable actor in the donor plugins, and the race names no ArmorRace to fall back on.");
                        break;
                    }

                    var why = donorRace.Value == raceKey
                        ? (view.RaceIsLeveled(npc) ? "race rolled from a leveled list, nearest by level" : "same race, nearest by level")
                        : $"via {RaceName(donorRace.Value, cache)}, nearest by level";

                    var donor = donors.ForRace(donorRace.Value, view.IntendedLevel(npc));
                    if (donor is null) break;

                    var target = state.PatchMod.Npcs.GetOrAddAsOverride(npc);
                    if (!npcPatcher.ApplyDonor(npc, target, donor, cls, why))
                        state.PatchMod.Npcs.Remove(npc.FormKey);
                    break;
                }
            }
        }

        // ------------------------------------------------------------------ races the mods define
        foreach (var race in order.PriorityOrder.Race().WinningOverrides())
        {
            if (!targets.Contains(race.FormKey.ModKey)) continue;

            var target = state.PatchMod.Races.GetOrAddAsOverride(race);
            var patched = racePatcher.StripGiantStomp(race, target);

            // A creature's armour rating, resistances, regeneration and damage all live on its RACE
            // (npcs.md §5.2 pattern B, §5.5), so a mod's own creature race needs bringing onto the ladder
            // or nothing else lands. Humanoid and child races are left alone: their actors are handled on
            // the bandit grid, and copying a playable race's ability list onto one would be wrong.
            var isHumanoid = race.Keywords?.Any(k => k.FormKey == StackData.ActorTypeNPC) == true;
            var isChild = race.Flags.HasFlag(Race.Flag.Child);

            if (!isHumanoid && !isChild && ResolveDonorRaceRecord(race, cache) is { } donorRace)
                patched |= racePatcher.Apply(race, target, donorRace);
            else if (!isHumanoid && !isChild)
                log.NeedsDecision($"race {race.EditorID ?? "<unnamed>"} ({race.FormKey}) names no ArmorRace and has no override — not patched.");

            if (!patched) state.PatchMod.Races.Remove(race.FormKey);
        }

        log.Summarise();
    }

    /// <summary>Rank levels are 3 / 7 / 10 / 12 / 19 / 24. Ties go to the higher rank: under-statting an
    /// enemy is the expensive mistake.</summary>
    private static int NearestRank(int level)
    {
        var best = 1;
        var bestDistance = int.MaxValue;
        for (var rank = 1; rank <= 6; rank++)
        {
            var distance = Math.Abs(StackData.RankLevels[rank] - level);
            if (distance <= bestDistance) { bestDistance = distance; best = rank; }
        }
        return best;
    }

    /// <summary>
    /// Which race's actors to take the balance from. A hand-written override wins; then the race's own
    /// <c>ArmorRace</c>.
    ///
    /// <c>ArmorRace</c> is the field a mod author sets to say "this race wears what THAT race wears", and
    /// it is the closest thing the format has to a declared parent — <c>BakaHorseRace</c> points at
    /// <c>HorseRace</c>, <c>BakaGiantOrcRace</c> at <c>OrcRace</c>. Following it is reading an authored
    /// answer, not guessing, which is why a custom race no longer needs a manual entry to be patched.
    /// </summary>
    private static FormKey? ResolveDonorRace(FormKey race, DonorIndex donors, ILinkCache cache)
    {
        var mapped = Config.RaceDonorOverrides
            .FirstOrDefault(o => o.TargetRace.FormKey == race && !o.DonorRace.IsNull);
        if (mapped is not null && donors.HasRace(mapped.DonorRace.FormKey)) return mapped.DonorRace.FormKey;

        if (donors.HasRace(race)) return race;

        var seen = new HashSet<FormKey> { race };
        var current = race;
        for (var depth = 0; depth < 4; depth++)
        {
            if (!cache.TryResolve<IRaceGetter>(current, out var record)) return null;
            if (record.ArmorRace.IsNull) return null;

            var parent = record.ArmorRace.FormKey;
            if (!seen.Add(parent)) return null;
            if (donors.HasRace(parent)) return parent;
            current = parent;
        }
        return null;
    }

    /// <summary>The race a mod-defined RACE should copy its balance from: a hand-written override, else
    /// its own <c>ArmorRace</c>.</summary>
    private static IRaceGetter? ResolveDonorRaceRecord(IRaceGetter race, ILinkCache cache)
    {
        var mapped = Config.RaceDonorOverrides
            .FirstOrDefault(o => o.TargetRace.FormKey == race.FormKey && !o.DonorRace.IsNull);
        if (mapped is not null && mapped.DonorRace.TryResolve(cache) is { } overridden) return overridden;

        return race.ArmorRace.IsNull ? null : race.ArmorRace.TryResolve(cache);
    }

    private static string RaceName(FormKey race, ILinkCache cache) =>
        cache.TryResolve<IRaceGetter>(race, out var r)
            ? $"{r.EditorID ?? "<unnamed>"} ({race})"
            : race.ToString();

    private static string Describe(INpcGetter npc) =>
        $"{npc.EditorID ?? npc.Name?.String ?? "<unnamed>"} ({npc.FormKey})";
}
